version: "3"
services:
  frontend:
    image: cryptosushi:frontend
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        UNIQYS_NODE_HOST: "uniqys-node"
        UNIQYS_NODE_PORT: "8080"
        DAPP_ENDPOINT: "http://localhost:3000"
    ports:
      - "3000:3000"
    environment:
      UNIQYS_NODE_HOST: "uniqys-node"
      UNIQYS_NODE_PORT: "8080"
      DAPP_ENDPOINT: "http://localhost:3000"
    volumes:
      - "/app/node_modules"
      - "./frontend:/app"

  uniqys-node:
    image: cryptosushi:uniqys-node
    build:
      context: server/uniqys-node
      dockerfile: Dockerfile
      args:
        LEVELDOWN_DIR: "/data/.leveldown"
    ports:
      - "8080:8080"
    environment:
      UNIQYS_APP_URL: "http://app:56080"
    volumes:
      - bc-store:/data/.leveldown
      - bc-config:/app/config
      - "./server/uniqys-node:/app"
      - "/app/node_modules"

  app:
    image: cryptosushi:app
    build:
      context: server/app
      dockerfile: Dockerfile
    depends_on:
      - frontend
    environment:
      HOST: "app"
      MEMCACHED_HOST: "uniqys-node"
      API_BASE: 'http://uniqys-node:56010'
      OPERATOR_ADDRESS: "767f8f53ad2fa6c78ca097fd3e331b4454f58188"
      SERVER: "gunicorn"
      WORKER_NUM: 9
      DEBUG: 'true'
      AUTO_RELOAD: 'true'
    volumes:
      - "./server/app:/app"
    stdin_open: true
    tty: true

volumes:
  bc-store:
  bc-config:

