version: "3"
services:
  frontend:
    image: cryptosushi:frontend
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        DAPP_HOST: "uniqys-node"
    ports:
      - "3000:3000"
    environment:
      DAPP_HOST: "uniqys-node"

  uniqys-node:
    image: cryptosushi:uniqys-node
    build:
      context: server/uniqys-node
      dockerfile: Dockerfile
      args:
        LEVELDOWN_DIR: "/data/.leveldown"
    ports:
      - "8080:8080"
    environment:
      UNIQYS_APP_URL: "http://app:56080"
    volumes:
      - bc-store:/data/.leveldown
      - bc-config:/app/config

  app:
    image: cryptosushi:app
    build:
      context: server/app
      dockerfile: Dockerfile
    environment:
      HOST: "app"
      MEMCACHED_HOST: "uniqys-node"
      API_BASE: 'http://uniqys-node:56010'
      OPERATOR_ADDRESS: "767f8f53ad2fa6c78ca097fd3e331b4454f58188"
    stdin_open: true
    tty: true

volumes:
  bc-store:
  bc-config: